# Generated by Django 3.2.8 on 2021-10-28 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount_of_upvotes',
            field=models.ManyToManyField(blank=True, related_name='posts_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
